name: hip
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip:
      - absl-py==2.1.0
      - accelerate==0.28.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attention-sinks==0.4.0
      - attrs==23.2.0
      - auto-gptq==0.7.1
      - axial-positional-embedding==0.2.1
      - bitsandbytes==0.43.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - codespell==2.2.6
      - coloredlogs==15.0.1
      - colt5-attention==0.10.20
      - contourpy==1.2.0
      - cupy-cuda12x==12.1.0
      - cycler==0.12.1
      - datasets==2.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dm-tree==0.1.8
      - einops==0.7.0
      - evaluate==0.4.1
      - fastapi==0.110.0
      - fastrlock==0.8.2
      - filelock==3.13.1
      - flash-attn==2.5.6
      - flatbuffers==24.3.7
      - fonttools==4.50.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - fuzzywuzzy==0.18.0
      - gast==0.5.4
      - gekko==1.1.0
      - google-pasta==0.2.0
      - grpcio==1.62.1
      - h11==0.14.0
      - h5py==3.10.0
      - hip-attention==0.0.1
      - httpcore==1.0.4
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - humanfriendly==10.0
      - idna==3.6
      - imageio==2.34.0
      - iniconfig==2.0.0
      - interegular==0.3.3
      - jieba==0.42.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - keras==3.0.5
      - kiwisolver==1.4.5
      - lark==1.1.9
      - lazy-loader==0.3
      - libclang==16.0.6
      - llvmlite==0.42.0
      - local-attention==1.9.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - mypy==0.991
      - mypy-extensions==1.0.0
      - namex==0.0.7
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - numba==0.59.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.133
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.3.2
      - openai==1.14.1
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - optimum==1.18.0
      - outlines==0.0.36
      - pandas==2.2.1
      - peft==0.9.0
      - performer-pytorch==1.1.4
      - pillow==10.2.0
      - pluggy==1.4.0
      - product-key-memory==0.2.10
      - prometheus-client==0.20.0
      - protobuf==4.25.3
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.1
      - pyarrow-hotfix==0.6
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pynvml==11.5.0
      - pypareto==0.3.0
      - pyparsing==3.1.2
      - pyrouge==0.1.3
      - pytest==8.1.1
      - pytest-asyncio==0.23.5.post1
      - pytest-forked==1.6.0
      - pytest-rerunfailures==14.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - ray==2.9.3
      - referencing==0.34.0
      - reformer-pytorch==1.4.4
      - regex==2023.12.25
      - requests==2.31.0
      - responses==0.18.0
      - rich==13.7.1
      - rouge==1.0.1
      - rouge-score==0.1.2
      - rpds-py==0.18.0
      - ruff==0.1.5
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - starlette==0.36.3
      - sympy==1.12
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-io-gcs-filesystem==0.36.0
      - termcolor==2.4.0
      - threadpoolctl==3.3.0
      - tifffile==2024.2.12
      - tokenizers==0.15.2
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.2.1
      - tqdm==4.66.2
      - transformers==4.39.2
      - triton==2.3.0
      - types-pyyaml==6.0.12.20240311
      - types-requests==2.31.0.20240311
      - types-setuptools==69.2.0.20240317
      - tzdata==2024.1
      - urllib3==2.2.1
      - uvicorn==0.28.0
      - uvloop==0.19.0
      - vllm==0.3.3+cu122
      - watchfiles==0.21.0
      - websockets==12.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - xformers==0.0.25
      - xxhash==3.4.1
      - yapf==0.32.0
      - yarl==1.9.4
