[build-system]
requires = [
    "setuptools>=49.4.0",
    "setuptools-scm",

    # Build dependencies. (Especially for flash-attn)
    "cmake>=3.21",
    "ninja",
    "packaging",
    "torch==2.5.1",
    "wheel",
]
build-backend = "setuptools.build_meta"

# Basic package info
[project]
name = "hip-attn"  # Name of package when installed using pip
version = "1.2.0"
description = "HiP Attention"
requires-python = ">=3.10, <3.13"
dependencies = [
    # Required
    "torch==2.5.1",
    "numba",
    "performer_pytorch",
    "peft",
    "seaborn",
    "sympy",
    "bitsandbytes",

    # CUDA 12
    "cupy-cuda12x",
    "nvtx",
]

[project.optional-dependencies]
research = [
    # Trainer
    "torchmetrics",
    "deepspeed",
    "lightning",
    "pytorch_lightning",
    "scikit-learn",

    # Dataset
    "torchtext",
    "datasets",

    # Eval
    "pypareto",
    "pyrouge",

    # Other dependencies
    "requests",
    "tqdm",
    "matplotlib",
    "numpy < 2.0.0",  # Numpy>=2.0 has breaking changes, see https://github.com/vllm-project/vllm/pull/5582/files
    "scikit-image",
    "wandb",
]

test = [  # Packages required for running the tests
    "hip-attn[research]",
]

sglang = [
    "sgl-kernel",
    # Needs adding `--find-links https://flashinfer.ai/whl/cu124/torch2.5/flashinfer-python`
    # For uv, see tool.uv.sources and tool.uv.index sections
    "flashinfer-python",

    "sglang[all] @ git+https://github.com/DeepAuto-AI/sglang.git@deepauto/release#subdirectory=python",

    # flash-attn
    "flash-attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.5cxx11abiFALSE-cp311-cp311-linux_x86_64.whl",
]

# You still need to install hip-attn[no_build_iso]
all = ["hip_attn[test,research,sglang]"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools]
packages = ["hip_attn", "hip_research"]

[tool.uv.sources]
flashinfer-python = [
  { index = "flashinfer_cu124_torch25" },
]
hip-attn = { workspace = true }

[tool.uv]
no-build-isolation-package = ["flash-attn"]

[[tool.uv.index]]
name = "flashinfer_cu124_torch25"
url = "https://flashinfer.ai/whl/cu124/torch2.5/"
explicit = true

[dependency-groups]
dev = [
    "hip-attn[all]",
]
