[project]
name = "hip-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bumsik Kim", email = "k.bumsik@gmail.com" }
]
requires-python = ">=3.10, <3.13"
dependencies = []

[project.scripts]
hip-research = "hip_research:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
